In [ ]:
"""Q1. What is the mathematical formula for a linear SVM?

    Ans: The mathematical formula for a linear SVM can be expressed as follows: y = (W^T · x + b), where y is the predicted class label, w is the weight vector, 
         x is the input vector, b is the bias term, and sign is the sign function.
"""

In [ ]:
"""Q2. What is the objective function of a linear SVM?

    Ans: The objective function of a linear SVM is to find the hyperplane that maximizes the margin between the two classes. This is achieved by minimizing the sum of the 
         squared norms of the weight vector subject to the constraint that each training example is classified correctly.
"""

In [ ]:
"""Q3. What is the kernel trick in SVM?

    Ans: The kernel trick in SVM is a method of transforming the input features of a linear SVM into a higher-dimensional space without actually computing the coordinates of 
         the data in that space. This allows non-linear decision boundaries to be learned, making SVMs more powerful and flexible for classification tasks.
"""

In [ ]:
"""Q4. What is the role of support vectors in SVM Explain with example.

    Ans: Support vectors are the training examples that lie closest to the decision boundary in an SVM. They are the critical points that define the location of the decision 
         boundary and are used to make predictions for new examples. The optimal decision boundary is determined by these support vectors, and examples that are not support 
         vectors do not contribute to the final solution. For example, in a binary classification task, there may be only a few support vectors that lie on or near the decision 
         boundary, while the rest of the training examples are far away from the boundary and do not affect the final solution.
"""

In [ ]:
"""Q5. Illustrate with examples and graphs of Hyperplane, Marginal plane, Soft margin and Hard margin in SVM?

    Ans: 1. Hyperplane: A hyperplane in SVM is a decision boundary that separates the two classes. In a 2D feature space, a hyperplane is a straight line, and in a 3D feature 
                space, it is a flat plane. The hyperplane is defined by a weight vector and a bias term, and the objective of SVM is to find the hyperplane that maximizes the 
                margin between the classes.
            Example: Suppose we have a dataset with two classes, represented by blue and red circles, and two features, x and y. We want to find the hyperplane that separates 
                the two classes.
         2. Marginal plane: The marginal plane in SVM is the plane that is equidistant from the positive and negative support vectors. It is defined by the sum of the weight 
                 vector and the bias term. The distance between the marginal plane and the hyperplane is the margin, and the objective of SVM is to maximize this margin. 
            Example: Suppose we have a dataset with two classes, represented by blue and red circles, and two features, x and y. We have found the hyperplane that separates 
                the two classes and the positive and negative support vectors.
         3. Soft margin: In some cases, the dataset may not be perfectly separable, and we need to allow for some misclassifications in order to find a good decision boundary. 
                 This is called a soft margin. The objective of SVM with a soft margin is to find a decision boundary that minimizes the number of misclassifications while 
                 still maximizing the margin.
            Example: Suppose we have a dataset with two classes, represented by blue and red circles, and two features, x and y. We want to find a decision boundary that 
                 minimizes the number of misclassifications while still maximizing the margin.
         4. Hard margin: If the dataset is perfectly separable, we can use a hard margin to find the decision boundary. A hard margin SVM tries to find the decision boundary 
                 that perfectly separates the two classes with no misclassifications.
            Example: Suppose we have a dataset with two classes, represented by blue and red circles, and two features, x and y. We want to find a decision boundary that
                 perfectly separates the two classes with no misclassifications.



"""

In [6]:
"""Q6. SVM Implementation through Iris dataset."""

import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

iris = sns.load_dataset('iris')
X = iris.iloc[:,:-1]
y = iris.iloc[:, -1]

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=69)

classifier = SVC(kernel='linear')
classifier.fit(X_train,y_train)
y_p = classifier.predict(X_test)

print(accuracy_score(y_test, y_p))
print(confusion_matrix(y_test, y_p))
print(classification_report(y_test, y_p))

p = {
    'C':[0.1,1,10,100,1000],
    'gamma':[1,0.1,0.01,0.001,0.0001],
    'kernel':['linear']
}

g = GridSearchCV(SVC(), param_grid=p, cv=5)
g.fit(X_train, y_train)
print(g.best_params_)
print(g.best_score_)
y_p2 = g.predict(X_test)
print(accuracy_score(y_test, y_p2))
print(confusion_matrix(y_test, y_p2))
print(classification_report(y_test, y_p2))

1.0
[[16  0  0]
 [ 0 12  0]
 [ 0  0 17]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        16
  versicolor       1.00      1.00      1.00        12
   virginica       1.00      1.00      1.00        17

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

{'C': 1, 'gamma': 1, 'kernel': 'linear'}
0.9714285714285715
1.0
[[16  0  0]
 [ 0 12  0]
 [ 0  0 17]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        16
  versicolor       1.00      1.00      1.00        12
   virginica       1.00      1.00      1.00        17

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

